import SwiftUI

struct Lesson: Identifiable {
    let id: Int
    let title: String
    let abbreviation: String
    let icon: String
    let difficulty: Difficulty
    let gradient: [Color]
    let content: String

    enum Difficulty: String {
        case beginner = "Beginner"
        case intermediate = "Intermediate"
        case expert = "Expert"
    }
}

struct LessonRepository {
    static let all: [Lesson] = [
        Lesson(id: 0, title: "Sundials & Shadows", abbreviation: "SUN", icon: "sun.max.fill", difficulty: .beginner,
               gradient: [FLColor.warmEmber, Color(red: 0.85, green: 0.35, blue: 0.1)],
               content: "The sundial is humanity's oldest timekeeping instrument, dating back to 1500 BCE in ancient Egypt. Obelisks cast shadows that moved predictably with the sun's position. The gnomon—the shadow-casting element—must be aligned with Earth's rotational axis (pointing toward the celestial pole) for accurate readings. Egyptian shadow clocks divided daytime into 12 temporal hours that varied in length with seasons. The hemicyclium, a concave sundial designed by Berossus around 300 BCE, improved accuracy by projecting shadows onto a curved surface. By the Roman era, portable sundials were common—Augustus had one installed in the Campus Martius using an Egyptian obelisk 30 meters tall. Sundials reveal a profound truth: our ancestors built precision instruments by observing nature's geometry."),

        Lesson(id: 1, title: "Water Clocks: Clepsydra", abbreviation: "WTR", icon: "drop.fill", difficulty: .beginner,
               gradient: [FLColor.biolumCyan, FLColor.deepSea],
               content: "Water clocks (clepsydrae) solved sundials' critical flaw: they work at night and on cloudy days. The simplest design—an outflow clepsydra—is a vessel with a small hole near the base. Water drains at a roughly constant rate, and markings on the interior wall indicate elapsed time. Ancient Egyptians used these by 1400 BCE. The Greek engineer Ctesibius of Alexandria (285–222 BCE) revolutionized the design with inflow clepsydrae featuring a float-and-pointer mechanism, feedback-regulated flow, and even gear-driven automata. In China, Su Song built a monumental astronomical clock tower in 1088 CE powered by a water-wheel escapement—a 12-meter tower with an armillary sphere, celestial globe, and five levels of rotating mannequins announcing time. Water clocks were the world's most accurate timekeepers for nearly 3000 years."),

        Lesson(id: 2, title: "Candle & Incense Clocks", abbreviation: "FIR", icon: "flame.fill", difficulty: .beginner,
               gradient: [Color(red: 0.95, green: 0.55, blue: 0.1), Color(red: 0.7, green: 0.2, blue: 0.05)],
               content: "King Alfred the Great of England (849–899 CE) is credited with standardizing candle clocks: candles of uniform thickness with evenly spaced markings, each segment representing a known time interval (typically 20 minutes per inch). Metal pins inserted at intervals would fall onto a metal plate below, creating an audible alarm—perhaps the first alarm clock. In East Asia, incense clocks took an extraordinary form: powdered incense trails laid in labyrinthine patterns on flat trays. A single trail could burn for days, with different scented incense at calculated intervals serving as olfactory time markers. Japanese geisha districts used incense clocks to bill clients—the length of a stick determined the session price. These clocks remind us that timekeeping need not be mechanical; chemistry and combustion are equally valid chronometric principles."),

        Lesson(id: 3, title: "Mechanical Escapement", abbreviation: "ESC", icon: "gearshape.2.fill", difficulty: .beginner,
               gradient: [FLColor.biolumViolet, Color(red: 0.3, green: 0.1, blue: 0.6)],
               content: "The verge-and-foliot escapement, appearing in European monasteries around 1270 CE, is the invention that launched mechanical horology. It converts continuous energy (a falling weight) into regulated, periodic motion. The verge is a vertical shaft with two pallets that alternately catch and release teeth on a crown wheel. The foliot—a horizontal bar with adjustable weights—controls the oscillation rate. This mechanism was accurate to about 15 minutes per day. The first major public clock appeared in Milan's church of Sant'Eustorgio (1309). By 1370, Heinrich von Wieck built the famous clock of the Palais de la Cité in Paris. The key insight: an escapement doesn't keep time—it regulates the release of stored energy. Every mechanical watch today, from a $50 Seiko to a $500,000 Patek Philippe, uses a descendant of this 750-year-old invention."),

        Lesson(id: 4, title: "Pendulum Revolution", abbreviation: "PND", icon: "metronome.fill", difficulty: .beginner,
               gradient: [FLColor.auroraA, FLColor.deepSea],
               content: "Galileo Galilei observed a swinging lamp in Pisa Cathedral around 1583 and timed its oscillations against his pulse, discovering isochronism: a pendulum's period depends only on its length, not its amplitude. He sketched pendulum clock designs but never built one. In 1656, Christiaan Huygens built the first working pendulum clock, instantly improving accuracy from 15 minutes/day to 15 seconds/day—a 60× improvement. Huygens discovered that a pendulum swinging along a cycloid curve (not a circular arc) is truly isochronous, and designed cycloidal cheeks to guide the suspension cord. His 1673 masterwork 'Horologium Oscillatorium' laid the mathematical foundations of oscillatory physics. The pendulum clock remained the world's most accurate timekeeper for 270 years, until quartz oscillators arrived in 1927. A one-meter pendulum swings with a period of almost exactly 2 seconds—a fact the French nearly used to define the meter."),

        Lesson(id: 5, title: "Marine Chronometers", abbreviation: "NAV", icon: "safari.fill", difficulty: .intermediate,
               gradient: [Color(red: 0.1, green: 0.3, blue: 0.6), FLColor.biolumCyan],
               content: "The Longitude Problem was the deadliest scientific challenge of the 18th century. Without accurate time at sea, navigators couldn't determine longitude, leading to catastrophic shipwrecks. In 1714, the British Parliament offered £20,000 (≈£3.5 million today) for a solution accurate to 30 nautical miles. John Harrison, a self-taught Yorkshire carpenter, spent 31 years building five marine chronometers (H1–H5). His H4, completed in 1759, was a revolutionary pocket-watch-sized instrument using a fast-beating balance wheel (5 beats/second), a remontoire (constant-force mechanism), bimetallic temperature compensation, and diamond pallets to reduce friction. On its 1762 trial voyage to Jamaica (81 days), H4 lost only 5.1 seconds—equivalent to 1.25 nautical miles of longitude error. Harrison essentially gave humanity the ability to map the entire world. Modern marine chronometers use quartz, but Harrison's principles of temperature compensation and constant-force escapements remain in high-end mechanical watchmaking."),

        Lesson(id: 6, title: "Quartz Crystal Oscillators", abbreviation: "QTZ", icon: "waveform.path", difficulty: .intermediate,
               gradient: [Color(red: 0.85, green: 0.85, blue: 0.9), Color(red: 0.4, green: 0.4, blue: 0.55)],
               content: "In 1880, Pierre and Jacques Curie discovered the piezoelectric effect in quartz: mechanical stress generates voltage, and conversely, applied voltage causes the crystal to deform. In 1927, Warren Marrison and J.W. Horton at Bell Labs built the first quartz clock. A precisely cut quartz crystal vibrates at 32,768 Hz (2^15) when energized, and a digital divider circuit counts oscillations to produce a 1-second pulse. This frequency was chosen because it's a power of 2, making binary division trivially simple—15 flip-flop circuits yield exactly 1 Hz. Quartz clocks are accurate to ~15 seconds per month. The Quartz Crisis (1969–1985) nearly destroyed the Swiss watch industry when Seiko introduced the Astron, the world's first quartz wristwatch. Today, over 1.5 billion quartz watches are produced annually. Temperature-compensated quartz (TCXO) and oven-controlled quartz (OCXO) achieve accuracy of 0.01 ppm—about 0.3 seconds per year."),

        Lesson(id: 7, title: "Atomic Clocks & Cesium", abbreviation: "ATM", icon: "atom", difficulty: .intermediate,
               gradient: [FLColor.biolumGreen, Color(red: 0.05, green: 0.5, blue: 0.3)],
               content: "In 1955, Louis Essen and Jack Parry at the UK's National Physical Laboratory built the first practical cesium atomic clock. It exploits the fact that cesium-133 atoms transition between two hyperfine ground states when exposed to microwave radiation at exactly 9,192,631,770 Hz. In 1967, the SI second was redefined as exactly 9,192,631,770 periods of this radiation—making cesium the literal definition of time. Modern cesium fountain clocks (like NIST-F2) cool atoms to near absolute zero using laser cooling, then launch them upward in a fountain. As atoms rise and fall through a microwave cavity, their interaction time increases, improving precision to ~1 second in 300 million years. GPS satellites each carry multiple atomic clocks (cesium and rubidium), and your phone's GPS position depends on nanosecond timing differences between satellite signals. Without atomic clocks, GPS would accumulate ~10 km of error per day."),

        Lesson(id: 8, title: "Optical Lattice Clocks", abbreviation: "OPT", icon: "light.beacon.max.fill", difficulty: .intermediate,
               gradient: [FLColor.biolumPink, FLColor.biolumViolet],
               content: "Optical lattice clocks are the most precise timekeepers ever built—accurate to 1 second in 15 billion years (longer than the universe's age). Instead of microwaves, they use visible light (optical frequencies ~500 THz) to probe atomic transitions in strontium or ytterbium atoms. Atoms are trapped in an optical lattice—a standing wave of laser light creating an egg-carton-like array of potential wells—at a magic wavelength where the trapping light doesn't shift the clock transition. Jun Ye's group at JILA (University of Colorado) demonstrated a strontium lattice clock in 2015 that could detect the gravitational redshift from raising the clock just 2 centimeters. NIST's ytterbium lattice clock with ~10,000 atoms achieved a fractional uncertainty of 1.4×10⁻¹⁸ in 2019. These clocks are so precise they could redefine the second itself and enable relativistic geodesy—mapping Earth's gravitational field by measuring time dilation."),

        Lesson(id: 9, title: "Time Zones & GMT", abbreviation: "GMT", icon: "globe.americas.fill", difficulty: .intermediate,
               gradient: [Color(red: 0.15, green: 0.4, blue: 0.25), FLColor.auroraC],
               content: "Before 1883, every city kept its own local solar time—the US alone had over 300 local times. Railroad accidents caused by time confusion (the 1853 Providence & Worcester collision killed 14) drove standardization. Sir Sandford Fleming, a Scottish-Canadian engineer, proposed a global system of 24 hourly time zones at the International Meridian Conference in Washington, D.C. in 1884, where Greenwich, England was chosen as the Prime Meridian (0° longitude). The vote was 22 in favor, 1 against (San Domingo), with France and Brazil abstaining. France didn't adopt Greenwich time until 1911, calling it 'Paris Mean Time retarded by 9 minutes 21 seconds.' The International Date Line follows the 180° meridian but zigzags to keep island nations unified. UTC (Coordinated Universal Time) replaced GMT in 1972, maintained by a weighted average of ~450 atomic clocks worldwide. Leap seconds are inserted to keep UTC within 0.9 seconds of Earth's irregular rotation."),

        Lesson(id: 10, title: "Einstein & Time Dilation", abbreviation: "REL", icon: "warp", difficulty: .expert,
               gradient: [Color(red: 0.6, green: 0.1, blue: 0.9), Color(red: 0.15, green: 0.05, blue: 0.4)],
               content: "Einstein's Special Relativity (1905) proved that time is not absolute: a moving clock ticks slower than a stationary one by a factor of √(1−v²/c²). At 90% of light speed, time passes at only 43.6% the normal rate. General Relativity (1915) showed gravity also dilates time: clocks run slower in stronger gravitational fields. GPS satellites orbit at 20,200 km altitude where gravity is weaker, causing their clocks to run ~45 microseconds/day faster than ground clocks. Their orbital velocity (3.87 km/s) causes a special-relativistic slowdown of ~7 μs/day. Net effect: satellite clocks gain ~38 μs/day. Without relativistic corrections, GPS positions would drift ~11 km/day. The Hafele–Keating experiment (1971) confirmed time dilation by flying cesium clocks on commercial airliners: eastbound clocks lost 59±10 ns, westbound gained 273±7 ns—matching predictions. Time dilation is not theoretical—it's an engineering constraint in every satellite, particle accelerator, and deep-space mission."),

        Lesson(id: 11, title: "Quantum Clocks & Future", abbreviation: "QNT", icon: "waveform.badge.magnifyingglass", difficulty: .expert,
               gradient: [FLColor.biolumCyan, FLColor.biolumPink],
               content: "Nuclear clocks—the next frontier—would use transitions in the thorium-229 nucleus rather than electron shells, potentially achieving 10⁻¹⁹ fractional uncertainty. In 2024, researchers at JILA demonstrated the first entanglement-enhanced optical clock, using quantum correlations between atoms to surpass the standard quantum limit. Quantum network clocks could synchronize via entangled photons over fiber-optic links, creating a 'quantum internet of time.' Proposed space missions like ACES (Atomic Clock Ensemble in Space) on the ISS aim to test fundamental physics using ultra-precise clocks in microgravity. Chip-scale atomic clocks (CSACs), developed by DARPA, shrink atomic clock technology to 17 cm³ at 120 mW power, enabling precision timing in drones, soldiers' backpacks, and underwater vehicles. The philosophical implications are staggering: if we can measure time to 10⁻²⁰ precision, we may detect fluctuations in fundamental constants, gravitational waves from distant sources, and perhaps even signatures of quantum gravity."),

        Lesson(id: 12, title: "Biological Clocks", abbreviation: "BIO", icon: "heart.circle.fill", difficulty: .expert,
               gradient: [Color(red: 0.8, green: 0.15, blue: 0.3), Color(red: 0.4, green: 0.05, blue: 0.2)],
               content: "Every living organism contains molecular clocks. In mammals, the suprachiasmatic nucleus (SCN)—a cluster of ~20,000 neurons in the hypothalamus—serves as the master circadian pacemaker. The molecular mechanism involves transcription-translation feedback loops: CLOCK and BMAL1 proteins activate Period (PER) and Cryptochrome (CRY) genes, whose protein products accumulate, form complexes, and inhibit their own transcription—a cycle taking ~24 hours. Jeffrey Hall, Michael Rosbash, and Michael Young won the 2017 Nobel Prize for deciphering this mechanism in Drosophila. Cyanobacteria have the simplest known clock: just three proteins (KaiA, KaiB, KaiC) can maintain a 24-hour phosphorylation cycle in a test tube with no gene expression needed. Deep-sea organisms without sunlight synchronize to tidal and lunar cycles. The naked mole-rat has a degraded circadian clock, matching its subterranean lifestyle."),

        Lesson(id: 13, title: "Calendar Systems", abbreviation: "CAL", icon: "calendar.badge.clock", difficulty: .expert,
               gradient: [FLColor.moltenGold, Color(red: 0.6, green: 0.4, blue: 0.05)],
               content: "The Gregorian calendar (1582) corrected the Julian calendar's 11-minute annual drift that had accumulated to 10 days by the 16th century. Pope Gregory XIII decreed that October 4, 1582 would be followed by October 15. The Gregorian leap year rule—divisible by 4, except centuries, except centuries divisible by 400—yields an average year of 365.2425 days vs. the tropical year of 365.24219 days, an error of 1 day in 3,236 years. The Islamic Hijri calendar is purely lunar (354 or 355 days), causing Ramadan to cycle through all seasons over 33 years. The Hebrew calendar is lunisolar, inserting a 13th month (Adar II) in 7 out of every 19 years (Metonic cycle). The Maya Long Count calendar used a vigesimal (base-20) system; the famous 'end date' of December 21, 2012 (13.0.0.0.0) was simply a baktun rollover—like an odometer resetting. The Ethiopian calendar has 13 months (12 of 30 days plus a 13th of 5-6 days) and is currently 7-8 years behind the Gregorian."),
    ]
}
