import Foundation

struct QuizContent {
    static func questions(for lessonTitle: String) -> [QuizQuestion] {
        guard let lesson = LessonRepository.all.first(where: { $0.title == lessonTitle }) else {
            return []
        }

        switch lesson.id {
        case 0: // Sundials & Shadows
            return [
                QuizQuestion(question: "What is the shadow-casting element of a sundial called?",
                             options: ["Gnomon", "Foliot", "Escapement", "Obelisk"],
                             correctIndex: 0),
                QuizQuestion(question: "When were the earliest sundials used in ancient Egypt?",
                             options: ["3000 BCE", "1500 BCE", "500 BCE", "100 CE"],
                             correctIndex: 1),
                QuizQuestion(question: "Who designed the hemicyclium around 300 BCE?",
                             options: ["Ctesibius", "Berossus", "Ptolemy", "Archimedes"],
                             correctIndex: 1),
                QuizQuestion(question: "How did Egyptian shadow clocks divide daytime?",
                             options: ["Into 10 equal hours", "Into 12 temporal hours", "Into 24 equal hours", "Into 8 watches"],
                             correctIndex: 1),
                QuizQuestion(question: "Toward which direction must the gnomon point for accurate readings?",
                             options: ["Due east", "The celestial pole", "The equator", "Due west"],
                             correctIndex: 1),
                QuizQuestion(question: "What shape was the hemicyclium sundial?",
                             options: ["Flat disk", "Concave bowl", "Cylinder", "Pyramid"],
                             correctIndex: 1),
                QuizQuestion(question: "What Roman emperor installed a sundial using a 30-meter obelisk?",
                             options: ["Julius Caesar", "Augustus", "Nero", "Trajan"],
                             correctIndex: 1),
                QuizQuestion(question: "Why did temporal hours vary in length throughout the year?",
                             options: ["Due to temperature changes", "Daytime duration changes with seasons", "Gnomon materials expanded", "Clock makers made errors"],
                             correctIndex: 1),
            ]

        case 1: // Water Clocks
            return [
                QuizQuestion(question: "What is another name for a water clock?",
                             options: ["Horologium", "Clepsydra", "Astrolabe", "Armillary"],
                             correctIndex: 1),
                QuizQuestion(question: "What critical flaw of sundials did water clocks solve?",
                             options: ["They were too expensive", "They couldn't work at night or on cloudy days", "They were too large", "They required skilled operators"],
                             correctIndex: 1),
                QuizQuestion(question: "Who revolutionized water clock design with inflow clepsydrae?",
                             options: ["Archimedes", "Ctesibius of Alexandria", "Su Song", "Hero of Alexandria"],
                             correctIndex: 1),
                QuizQuestion(question: "How tall was Su Song's astronomical clock tower?",
                             options: ["5 meters", "8 meters", "12 meters", "20 meters"],
                             correctIndex: 2),
                QuizQuestion(question: "For how many years were water clocks the most accurate timekeepers?",
                             options: ["500 years", "1000 years", "2000 years", "Nearly 3000 years"],
                             correctIndex: 3),
                QuizQuestion(question: "When did ancient Egyptians begin using water clocks?",
                             options: ["3000 BCE", "1400 BCE", "500 BCE", "200 CE"],
                             correctIndex: 1),
                QuizQuestion(question: "What did an outflow clepsydra use to measure time?",
                             options: ["A spinning wheel", "Water draining through a small hole", "Floating magnets", "Steam pressure"],
                             correctIndex: 1),
                QuizQuestion(question: "What astronomical instrument did Su Song's tower include?",
                             options: ["A telescope", "An armillary sphere", "A sextant", "A compass"],
                             correctIndex: 1),
            ]

        case 2: // Candle & Incense Clocks
            return [
                QuizQuestion(question: "Who is credited with standardizing candle clocks?",
                             options: ["Charlemagne", "King Alfred the Great", "William the Conqueror", "Henry VIII"],
                             correctIndex: 1),
                QuizQuestion(question: "What created the audible alarm in candle clocks?",
                             options: ["A bell mechanism", "Metal pins falling onto a plate", "A water drip", "A wind chime"],
                             correctIndex: 1),
                QuizQuestion(question: "What form did East Asian incense clocks take?",
                             options: ["Burning candles in water", "Incense trails in labyrinthine patterns", "Heated metal plates", "Smoking chimneys"],
                             correctIndex: 1),
                QuizQuestion(question: "How did Japanese geisha districts use incense clocks?",
                             options: ["For meditation timing", "To bill clients based on stick length", "For tea ceremony timing", "For music tempo"],
                             correctIndex: 1),
                QuizQuestion(question: "How much time did each inch of King Alfred's candles represent?",
                             options: ["10 minutes", "20 minutes", "30 minutes", "1 hour"],
                             correctIndex: 1),
                QuizQuestion(question: "What served as olfactory time markers in incense clocks?",
                             options: ["Colored flames", "Different scented incense at intervals", "Smoke rings", "Temperature changes"],
                             correctIndex: 1),
                QuizQuestion(question: "When did King Alfred the Great live?",
                             options: ["500–560 CE", "700–780 CE", "849–899 CE", "1000–1066 CE"],
                             correctIndex: 2),
            ]

        case 3: // Mechanical Escapement
            return [
                QuizQuestion(question: "When did the verge-and-foliot escapement appear?",
                             options: ["Around 900 CE", "Around 1270 CE", "Around 1500 CE", "Around 1650 CE"],
                             correctIndex: 1),
                QuizQuestion(question: "What is the foliot in a verge-and-foliot escapement?",
                             options: ["A vertical shaft", "A crown wheel", "A horizontal bar with adjustable weights", "A pendulum"],
                             correctIndex: 2),
                QuizQuestion(question: "How accurate was the verge-and-foliot escapement?",
                             options: ["About 1 minute per day", "About 15 minutes per day", "About 1 hour per day", "About 15 seconds per day"],
                             correctIndex: 1),
                QuizQuestion(question: "What does an escapement actually do?",
                             options: ["Creates energy", "Stores time", "Regulates the release of stored energy", "Measures temperature"],
                             correctIndex: 2),
                QuizQuestion(question: "Where did the first major public clock appear?",
                             options: ["London", "Paris", "Milan", "Rome"],
                             correctIndex: 2),
                QuizQuestion(question: "What energy source powered early mechanical clocks?",
                             options: ["A spring", "A falling weight", "Water pressure", "Wind"],
                             correctIndex: 1),
                QuizQuestion(question: "Who built the famous clock of the Palais de la Cité in 1370?",
                             options: ["Leonardo da Vinci", "Heinrich von Wieck", "Roger Bacon", "Giovanni de' Dondi"],
                             correctIndex: 1),
                QuizQuestion(question: "What is the verge in a verge-and-foliot?",
                             options: ["A horizontal beam", "A vertical shaft with pallets", "A crown-shaped gear", "A pendulum rod"],
                             correctIndex: 1),
            ]

        case 4: // Pendulum Revolution
            return [
                QuizQuestion(question: "Who discovered pendulum isochronism?",
                             options: ["Newton", "Galileo Galilei", "Christiaan Huygens", "Robert Hooke"],
                             correctIndex: 1),
                QuizQuestion(question: "What does isochronism mean for pendulums?",
                             options: ["Period depends on mass", "Period depends only on length, not amplitude", "Period depends on temperature", "Period depends on material"],
                             correctIndex: 1),
                QuizQuestion(question: "Who built the first working pendulum clock?",
                             options: ["Galileo Galilei", "Isaac Newton", "Christiaan Huygens", "Robert Boyle"],
                             correctIndex: 2),
                QuizQuestion(question: "By how much did the pendulum clock improve accuracy?",
                             options: ["10×", "30×", "60×", "100×"],
                             correctIndex: 2),
                QuizQuestion(question: "What is the period of a one-meter pendulum?",
                             options: ["1 second", "Almost exactly 2 seconds", "3 seconds", "0.5 seconds"],
                             correctIndex: 1),
                QuizQuestion(question: "What curve makes a pendulum truly isochronous?",
                             options: ["Circular arc", "Parabola", "Cycloid", "Ellipse"],
                             correctIndex: 2),
                QuizQuestion(question: "Where was Galileo when he observed the swinging lamp?",
                             options: ["Rome's Colosseum", "Pisa Cathedral", "Florence's Duomo", "Venice's Basilica"],
                             correctIndex: 1),
                QuizQuestion(question: "For how many years did the pendulum clock remain the most accurate?",
                             options: ["100 years", "170 years", "270 years", "400 years"],
                             correctIndex: 2),
            ]

        case 5: // Marine Chronometers
            return [
                QuizQuestion(question: "What was the Longitude Problem about?",
                             options: ["Measuring latitude at sea", "Determining longitude without accurate time", "Building faster ships", "Mapping ocean currents"],
                             correctIndex: 1),
                QuizQuestion(question: "How much did the British Parliament offer for a longitude solution?",
                             options: ["£5,000", "£10,000", "£20,000", "£50,000"],
                             correctIndex: 2),
                QuizQuestion(question: "What was John Harrison's profession?",
                             options: ["A naval officer", "A university professor", "A self-taught carpenter", "A royal astronomer"],
                             correctIndex: 2),
                QuizQuestion(question: "How much time did H4 lose over 81 days at sea?",
                             options: ["1 minute", "30 seconds", "5.1 seconds", "1 second"],
                             correctIndex: 2),
                QuizQuestion(question: "How many marine chronometers did Harrison build in total?",
                             options: ["3 (H1–H3)", "4 (H1–H4)", "5 (H1–H5)", "6 (H1–H6)"],
                             correctIndex: 2),
                QuizQuestion(question: "What beat rate did the H4 use per second?",
                             options: ["1 beat", "2 beats", "5 beats", "10 beats"],
                             correctIndex: 2),
                QuizQuestion(question: "What disaster helped motivate the Longitude Act of 1714?",
                             options: ["Fire of London", "Catastrophic shipwrecks from navigation errors", "A volcanic eruption", "Plague outbreaks"],
                             correctIndex: 1),
                QuizQuestion(question: "What mechanism in H4 provided constant force?",
                             options: ["A pendulum", "A remontoire", "A flywheel", "A hydraulic pump"],
                             correctIndex: 1),
            ]

        case 6: // Quartz Crystal Oscillators
            return [
                QuizQuestion(question: "What effect do quartz crystals use for timekeeping?",
                             options: ["Electromagnetic", "Piezoelectric", "Thermoelectric", "Photoelectric"],
                             correctIndex: 1),
                QuizQuestion(question: "At what frequency does a standard quartz crystal vibrate?",
                             options: ["1,000 Hz", "10,000 Hz", "32,768 Hz", "100,000 Hz"],
                             correctIndex: 2),
                QuizQuestion(question: "Why was 32,768 Hz chosen?",
                             options: ["It's the most stable frequency", "It's a power of 2 (2¹⁵)", "It produces the best sound", "It's the cheapest to produce"],
                             correctIndex: 1),
                QuizQuestion(question: "What was the 'Quartz Crisis'?",
                             options: ["A shortage of quartz crystals", "Quartz clocks nearly destroyed the Swiss watch industry", "Quartz clocks were banned", "Quartz was found to be radioactive"],
                             correctIndex: 1),
                QuizQuestion(question: "What was the first quartz wristwatch?",
                             options: ["Rolex Oyster", "Seiko Astron", "Casio F-91W", "Timex Ironman"],
                             correctIndex: 1),
                QuizQuestion(question: "Who discovered the piezoelectric effect in quartz?",
                             options: ["Thomas Edison", "Pierre and Jacques Curie", "Nikola Tesla", "Michael Faraday"],
                             correctIndex: 1),
                QuizQuestion(question: "How many flip-flop circuits divide 32,768 Hz to 1 Hz?",
                             options: ["8", "10", "15", "20"],
                             correctIndex: 2),
                QuizQuestion(question: "How many quartz watches are produced globally each year?",
                             options: ["~100 million", "~500 million", "~1.5 billion", "~5 billion"],
                             correctIndex: 2),
            ]

        case 7: // Atomic Clocks & Cesium
            return [
                QuizQuestion(question: "How many oscillations of cesium-133 define one second?",
                             options: ["1,000,000", "9,192,631,770", "32,768", "299,792,458"],
                             correctIndex: 1),
                QuizQuestion(question: "When was the SI second redefined using cesium?",
                             options: ["1955", "1960", "1967", "1972"],
                             correctIndex: 2),
                QuizQuestion(question: "What technique do modern cesium fountain clocks use?",
                             options: ["Magnetic compression", "Laser cooling", "Microwave heating", "Electrical acceleration"],
                             correctIndex: 1),
                QuizQuestion(question: "How much GPS error would accumulate daily without atomic clocks?",
                             options: ["1 meter", "100 meters", "1 km", "~10 km"],
                             correctIndex: 3),
                QuizQuestion(question: "Who built the first practical cesium atomic clock in 1955?",
                             options: ["Albert Einstein", "Essen and Parry", "Richard Feynman", "Niels Bohr"],
                             correctIndex: 1),
                QuizQuestion(question: "What type of radiation does cesium-133 respond to?",
                             options: ["Gamma rays", "Infrared", "Microwave", "Ultraviolet"],
                             correctIndex: 2),
                QuizQuestion(question: "How accurate is NIST-F2?",
                             options: ["1 sec in 1 million years", "1 sec in 100 million years", "1 sec in 300 million years", "1 sec in 1 billion years"],
                             correctIndex: 2),
            ]

        case 8: // Optical Lattice Clocks
            return [
                QuizQuestion(question: "How accurate are optical lattice clocks?",
                             options: ["1 second in 1 million years", "1 second in 100 million years", "1 second in 15 billion years", "1 second in 1 billion years"],
                             correctIndex: 2),
                QuizQuestion(question: "What frequency range do optical clocks use?",
                             options: ["Radio (~1 MHz)", "Microwave (~9 GHz)", "Infrared (~100 THz)", "Visible light (~500 THz)"],
                             correctIndex: 3),
                QuizQuestion(question: "What altitude change could a strontium lattice clock detect?",
                             options: ["2 meters", "2 centimeters", "2 millimeters", "2 kilometers"],
                             correctIndex: 1),
                QuizQuestion(question: "What is the 'magic wavelength' in optical lattice clocks?",
                             options: ["The wavelength that maximizes trap depth", "The wavelength where trapping light doesn't shift the clock transition", "The shortest visible wavelength", "The wavelength of cesium emission"],
                             correctIndex: 1),
                QuizQuestion(question: "What element does Jun Ye's JILA clock use?",
                             options: ["Cesium", "Rubidium", "Strontium", "Thorium"],
                             correctIndex: 2),
                QuizQuestion(question: "What field could ultra-precise clocks enable by measuring gravity via time dilation?",
                             options: ["Quantum computing", "Relativistic geodesy", "Nuclear fusion", "Dark matter detection"],
                             correctIndex: 1),
                QuizQuestion(question: "How many atoms did NIST's ytterbium lattice clock use?",
                             options: ["~100", "~1,000", "~10,000", "~1,000,000"],
                             correctIndex: 2),
            ]

        case 9: // Time Zones & GMT
            return [
                QuizQuestion(question: "How many local times existed in the US before 1883?",
                             options: ["24", "50", "Over 300", "12"],
                             correctIndex: 2),
                QuizQuestion(question: "Who proposed the global 24-timezone system?",
                             options: ["Albert Einstein", "Sir Sandford Fleming", "James Watt", "Benjamin Franklin"],
                             correctIndex: 1),
                QuizQuestion(question: "When was Greenwich chosen as the Prime Meridian?",
                             options: ["1850", "1884", "1900", "1920"],
                             correctIndex: 1),
                QuizQuestion(question: "When did France adopt Greenwich time?",
                             options: ["1884", "1900", "1911", "1925"],
                             correctIndex: 2),
                QuizQuestion(question: "How many atomic clocks maintain UTC worldwide?",
                             options: ["~50", "~150", "~300", "~450"],
                             correctIndex: 3),
                QuizQuestion(question: "What replaced GMT as the international time standard in 1972?",
                             options: ["EST", "UTC", "TAI", "PST"],
                             correctIndex: 1),
                QuizQuestion(question: "What are leap seconds used for?",
                             options: ["Correcting GPS drift", "Keeping UTC within 0.9 sec of Earth's rotation", "Adjusting for daylight saving", "Syncing with the Moon"],
                             correctIndex: 1),
                QuizQuestion(question: "What 1853 disaster drove US railroad time standardization?",
                             options: ["Great Chicago Fire", "Providence & Worcester collision", "San Francisco earthquake", "Mississippi flood"],
                             correctIndex: 1),
            ]

        case 10: // Einstein & Time Dilation
            return [
                QuizQuestion(question: "In Special Relativity, what factor describes time dilation?",
                             options: ["√(1+v²/c²)", "√(1−v²/c²)", "v/c", "c/v"],
                             correctIndex: 1),
                QuizQuestion(question: "At 90% of light speed, time passes at what rate compared to stationary?",
                             options: ["90%", "50%", "43.6%", "10%"],
                             correctIndex: 2),
                QuizQuestion(question: "What is the net daily time correction needed for GPS satellites?",
                             options: ["~7 μs", "~38 μs", "~45 μs", "~100 μs"],
                             correctIndex: 1),
                QuizQuestion(question: "What experiment confirmed time dilation using airliners in 1971?",
                             options: ["Michelson-Morley", "Hafele-Keating", "Pound-Rebka", "Ives-Stilwell"],
                             correctIndex: 1),
                QuizQuestion(question: "When did Einstein publish Special Relativity?",
                             options: ["1895", "1905", "1915", "1925"],
                             correctIndex: 1),
                QuizQuestion(question: "General Relativity showed that clocks run slower in…?",
                             options: ["Weaker gravity", "Stronger gravity", "Higher altitude", "Lower temperature"],
                             correctIndex: 1),
                QuizQuestion(question: "How much would GPS positions drift per day without relativistic corrections?",
                             options: ["~100 m", "~1 km", "~11 km", "~100 km"],
                             correctIndex: 2),
            ]

        case 11: // Quantum Clocks & Future
            return [
                QuizQuestion(question: "What element would nuclear clocks use?",
                             options: ["Cesium-133", "Strontium-87", "Thorium-229", "Ytterbium-171"],
                             correctIndex: 2),
                QuizQuestion(question: "What size are chip-scale atomic clocks (CSACs)?",
                             options: ["1 cm³", "17 cm³", "100 cm³", "1,000 cm³"],
                             correctIndex: 1),
                QuizQuestion(question: "What quantum property enhances the latest optical clocks?",
                             options: ["Superposition", "Tunneling", "Entanglement", "Interference"],
                             correctIndex: 2),
                QuizQuestion(question: "What might 10⁻²⁰ precision help detect?",
                             options: ["Dark energy", "Quantum gravity signatures", "Parallel universes", "Magnetic monopoles"],
                             correctIndex: 1),
                QuizQuestion(question: "What space mission aims to test ultra-precise clocks in microgravity?",
                             options: ["Hubble", "ACES on the ISS", "Voyager 3", "James Webb"],
                             correctIndex: 1),
                QuizQuestion(question: "How much power does a CSAC consume?",
                             options: ["12 mW", "120 mW", "1.2 W", "12 W"],
                             correctIndex: 1),
                QuizQuestion(question: "What organization developed CSAC technology?",
                             options: ["NASA", "CERN", "DARPA", "ESA"],
                             correctIndex: 2),
            ]

        case 12: // Biological Clocks
            return [
                QuizQuestion(question: "What brain structure serves as the master circadian pacemaker?",
                             options: ["Hippocampus", "Suprachiasmatic nucleus (SCN)", "Pineal gland", "Cerebellum"],
                             correctIndex: 1),
                QuizQuestion(question: "Which proteins activate PER and CRY genes?",
                             options: ["KaiA and KaiB", "CLOCK and BMAL1", "Rhodopsin and Melanopsin", "Myosin and Actin"],
                             correctIndex: 1),
                QuizQuestion(question: "How many proteins make up the cyanobacterial clock?",
                             options: ["One", "Two", "Three", "Five"],
                             correctIndex: 2),
                QuizQuestion(question: "Who won the 2017 Nobel Prize for circadian clock research?",
                             options: ["Francis Crick", "Hall, Rosbash, and Young", "Watson and Crick", "Jennifer Doudna"],
                             correctIndex: 1),
                QuizQuestion(question: "How many neurons make up the SCN?",
                             options: ["~2,000", "~20,000", "~200,000", "~2,000,000"],
                             correctIndex: 1),
                QuizQuestion(question: "What animal has a degraded circadian clock?",
                             options: ["Owl", "Bat", "Naked mole-rat", "Deep-sea fish"],
                             correctIndex: 2),
                QuizQuestion(question: "What cycle do deep-sea organisms without sunlight synchronize to?",
                             options: ["Solar cycle", "Tidal and lunar cycles", "Geomagnetic storms", "Thermal vents"],
                             correctIndex: 1),
            ]

        case 13: // Calendar Systems
            return [
                QuizQuestion(question: "Why was the Gregorian calendar introduced?",
                             options: ["To add more holidays", "To correct the Julian calendar's 10-day drift", "To standardize week length", "To synchronize with the Chinese calendar"],
                             correctIndex: 1),
                QuizQuestion(question: "What is the Gregorian leap year rule?",
                             options: ["Every 4 years, no exceptions", "Divisible by 4, except centuries, except centuries divisible by 400", "Every 5 years", "Divisible by 4 and 100"],
                             correctIndex: 1),
                QuizQuestion(question: "How often does Ramadan cycle through all seasons in the Islamic calendar?",
                             options: ["Every 10 years", "Every 19 years", "Every 33 years", "Every 50 years"],
                             correctIndex: 2),
                QuizQuestion(question: "How many months does the Ethiopian calendar have?",
                             options: ["12", "13", "14", "10"],
                             correctIndex: 1),
                QuizQuestion(question: "What was the Maya 2012 date really about?",
                             options: ["End of the world", "A baktun rollover", "Solar eclipse", "Planetary alignment"],
                             correctIndex: 1),
                QuizQuestion(question: "What date follows October 4, 1582 in the Gregorian calendar?",
                             options: ["October 5", "October 10", "October 15", "November 1"],
                             correctIndex: 2),
                QuizQuestion(question: "What is the Metonic cycle used in the Hebrew calendar?",
                             options: ["7-year cycle", "12-year cycle", "19-year cycle", "33-year cycle"],
                             correctIndex: 2),
                QuizQuestion(question: "How many years behind the Gregorian is the Ethiopian calendar?",
                             options: ["3–4 years", "7–8 years", "12–13 years", "100 years"],
                             correctIndex: 1),
            ]

        default:
            return []
        }
    }

    // MARK: - Gauntlet-Exclusive Bonus Questions

    /// Cross-topic and advanced questions that only appear in the Gauntlet mode
    static let gauntletBonusQuestions: [QuizQuestion] = [
        // Cross-topic connections
        QuizQuestion(question: "Which came first: the water clock or the sundial?",
                     options: ["Water clock", "Sundial", "They appeared simultaneously", "Neither — candle clocks came first"],
                     correctIndex: 1),
        QuizQuestion(question: "How many times more accurate is an optical lattice clock than a cesium atomic clock?",
                     options: ["~10×", "~100×", "~1,000×", "~50,000×"],
                     correctIndex: 3),
        QuizQuestion(question: "If you traveled at 99.99% the speed of light for 1 year (your time), how much time passes on Earth?",
                     options: ["1 year", "~7 years", "~71 years", "~700 years"],
                     correctIndex: 2),
        QuizQuestion(question: "What do Harrison's H4 and a modern Rolex share in common?",
                     options: ["Both use pendulums", "Both use high-beat balance wheels", "Both are solar-powered", "Both use quartz"],
                     correctIndex: 1),
        QuizQuestion(question: "Which technology directly enabled the Age of Exploration?",
                     options: ["Pendulum clocks", "Marine chronometers", "Atomic clocks", "Quartz oscillators"],
                     correctIndex: 1),
        QuizQuestion(question: "Approximately how many seconds are in one year?",
                     options: ["~3.15 million", "~31.5 million", "~315 million", "~3.15 billion"],
                     correctIndex: 1),

        // Tricky / deep knowledge
        QuizQuestion(question: "Why can't pendulum clocks work on a ship at sea?",
                     options: ["Salt corrodes the gears", "The rocking disrupts the pendulum's swing", "Humidity stops the mechanism", "Magnetic interference from the ocean"],
                     correctIndex: 1),
        QuizQuestion(question: "What is a 'complication' in watchmaking?",
                     options: ["A defect in the mechanism", "Any function beyond basic timekeeping", "A type of gear failure", "An expensive repair"],
                     correctIndex: 1),
        QuizQuestion(question: "What phenomenon causes GPS clocks to tick faster than ground clocks?",
                     options: ["Special relativity only", "General relativity (weaker gravity in orbit)", "Magnetic field variation", "Solar radiation pressure"],
                     correctIndex: 1),
        QuizQuestion(question: "Which country was the last major nation to adopt the Gregorian calendar?",
                     options: ["Russia (1918)", "Greece (1923)", "Turkey (1926)", "Saudi Arabia (2016)"],
                     correctIndex: 2),
        QuizQuestion(question: "How does a leap second differ from a leap year?",
                     options: ["It's added to February", "It's a single second added to UTC to sync with Earth's rotation", "It happens every 4 years", "It only affects atomic clocks"],
                     correctIndex: 1),
        QuizQuestion(question: "What frequency does the BBC's 'pips' time signal broadcast at?",
                     options: ["440 Hz", "1000 Hz", "32,768 Hz", "9,192,631,770 Hz"],
                     correctIndex: 1),
        QuizQuestion(question: "The word 'clock' comes from the medieval Latin 'clocca'. What does it mean?",
                     options: ["Circle", "Bell", "Tower", "Shadow"],
                     correctIndex: 1),
        QuizQuestion(question: "If atomic clocks are so precise, why do we still need leap seconds?",
                     options: ["Atomic clocks drift over time", "Earth's rotation is irregular and gradually slowing", "The Sun's gravity fluctuates", "GPS satellites interfere with UTC"],
                     correctIndex: 1),
        QuizQuestion(question: "What is 'horological' short for?",
                     options: ["The study of horror films", "The science of time measurement", "The study of star positions", "The science of sound waves"],
                     correctIndex: 1),
        QuizQuestion(question: "How many time zones does China officially use?",
                     options: ["1", "3", "5", "8"],
                     correctIndex: 0),
        QuizQuestion(question: "What ancient civilization used a 360-day calendar plus 5 'unlucky' days?",
                     options: ["Roman", "Egyptian", "Maya", "Babylonian"],
                     correctIndex: 1),
        QuizQuestion(question: "Which clock component stores energy in a mechanical watch?",
                     options: ["The escapement", "The mainspring", "The balance wheel", "The crystal"],
                     correctIndex: 1),
        QuizQuestion(question: "What is the 'equation of time'?",
                     options: ["E=mc²", "The difference between sundial time and mean solar time", "The formula for pendulum period", "The cesium frequency formula"],
                     correctIndex: 1),
        QuizQuestion(question: "Approximately how old is the oldest known calendar artifact?",
                     options: ["~5,000 years", "~10,000 years", "~30,000 years", "~100,000 years"],
                     correctIndex: 2),
    ]
}
